# Generated by Django 3.2 on 2024-06-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='url',
            field=models.URLField(default='https://remoteok.io/remote-jobs.rss', verbose_name=255),
            preserve_default=False,
        ),
    ]
