# Generated by Django 3.2 on 2024-06-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rssfeed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='url',
            field=models.URLField(),
        ),
    ]
